steps:
  # running build for frontend app
  - name: "gcr.io/visualexp-a7d2c/firebase:latest"
    entrypoint: "bash"
    args:
      - "-c"
      - "source /root/.bashrc && npm install --legacy-peer-deps && npm run build:prod"

  # running install for backend
  - name: "gcr.io/visualexp-a7d2c/firebase:latest"
    entrypoint: "bash"
    args:
      - "-c"
      - "source /root/.bashrc && cd functions && npm install --legacy-peer-deps"

  # running firebase deploy
  - name: "gcr.io/visualexp-a7d2c/firebase:latest"
    entrypoint: "bash"
    args:
      - "-c"
      - "source /root/.bashrc && firebase --debug deploy"
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

serviceAccount: "projects/visualexp-a7d2c/serviceAccounts/114329020973802572254"

timeout: 2000s
