steps:
  # running build for frontend app
  - name: "gcr.io/visualexp-a7d2c/firebase:latest"
    entrypoint: "bash"
    args:
      [
        "-c",
        'source /root/.bashrc && npm install --legacy-peer-deps && npm run build:prod'
      ]
  # running install for backend
  - name: "gcr.io/visualexp-a7d2c/firebase:latest"
    entrypoint: "bash"
    args:
      [
        "-c",
        'source /root/.bashrc && cd functions && npm install --legacy-peer-deps'
      ]
  # running firebase deploy
  - name: "gcr.io/visualexp-a7d2c/firebase:latest"
    entrypoint: "bash"
    args:
      [
        "-c",
        'echo $$VISUALEXP_PROD | base64 -d > functions/onecademy-dev-firebase-adminsdk-91m0g-0f326557b6.json && source /root/.bashrc && export ONECADEMYCRED_PROJECT_ID=$$ONECADEMYCRED_PROJECT_ID && export ONECADEMYCRED_TYPE=$$ONECADEMYCRED_TYPE && export ONECADEMYCRED_PRIVATE_KEY_ID=$$ONECADEMYCRED_PRIVATE_KEY_ID && export ONECADEMYCRED_PRIVATE_KEY="$$ONECADEMYCRED_PRIVATE_KEY" && export ONECADEMYCRED_CLIENT_EMAIL=$$ONECADEMYCRED_CLIENT_EMAIL && export ONECADEMYCRED_CLIENT_ID=$$ONECADEMYCRED_CLIENT_ID && export ONECADEMYCRED_AUTH_URI=$$ONECADEMYCRED_AUTH_URI && export ONECADEMYCRED_TOKEN_URI=$$ONECADEMYCRED_TOKEN_URI && export ONECADEMYCRED_AUTH_PROVIDER_X509_CERT_URL=$$ONECADEMYCRED_AUTH_PROVIDER_X509_CERT_URL && export ONECADEMYCRED_CLIENT_X509_CERT_URL=$$ONECADEMYCRED_CLIENT_X509_CERT_URL && export ONECADEMYCRED_STORAGE_BUCKET=$$ONECADEMYCRED_STORAGE_BUCKET && export ONECADEMYCRED_DATABASE_URL=$$ONECADEMYCRED_DATABASE_URL && firebase --debug deploy'
      ]
    secretEnv: ['VISUALEXP_PROD']
availableSecrets:
  secretManager:
  - versionName: projects/visualexp-a7d2c/secrets/VISUALEXP_PROD/versions/latest
    env: 'VISUALEXP_PROD'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
serviceAccount: 'projects/visualexp-a7d2c/serviceAccounts/114329020973802572254'
timeout: 2000s
