export default [
  {
    stem: "How can 1Cademy help us?",
    a: "Through learning backwards like researchers",
    b: "Joining/forming multi-school research communities",
    c: "Passing standardized exams",
    d: "Deepening our learning by thinking through prerequisites necessary to learn each concept",
    e: "Better scheduling our studying sessions",
    f: "Learning from each other the more effective ways to learn each concept",
    g: "Collaboratively developing learning pathways to learn each concept",
    h: "Crowdsourcing our learning",
    i: "Learning through teaching others",
    j: "Improving exploratory search",
    k: "A consensus-based collaboration mechanism where alternative or even competing perspectives are placed side-by-side so that one can easily compare and contrast them to learn and rationalize each topic in different contexts.",
    answers: [a, b, d, f, g, h, i, j, k],
  },
  {
    stem: "Why do we pay for textbooks and online courses when everything is already explained somewhere on the Internet?",
    a: "Because we cannot find the explanations on the Internet.",
    b: "Because we are lazy!",
    c: "Because we don't know how to use the Internet efficiently.",
    d: "Because the explanations on the Internet are not free.",
    e: "Because the explanations on the Internet are incorrect.",
    f: "Because the explanations on the Internet do not provide us with learning pathways.",
    g: "Because without a textbook or course structure, we don't know .",
    answers: [a, b, d, f, g, h, i, j, k],
  },
];
