steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        'docker build -t gcr.io/visualexp-a7d2c/knowledge --build-arg=ONECADEMYCRED_PROJECT_ID="$${ONECADEMYCRED_PROJECT_ID}" --build-arg=ONECADEMYCRED_PRIVATE_KEY_ID="$${ONECADEMYCRED_PRIVATE_KEY_ID}" --build-arg=ONECADEMYCRED_PRIVATE_KEY="$${ONECADEMYCRED_PRIVATE_KEY}" --build-arg=ONECADEMYCRED_CLIENT_EMAIL="$${ONECADEMYCRED_CLIENT_EMAIL}" --build-arg=ONECADEMYCRED_CLIENT_ID="$${ONECADEMYCRED_CLIENT_ID}" --build-arg=ONECADEMYCRED_CLIENT_X509_CERT_URL="$${ONECADEMYCRED_CLIENT_X509_CERT_URL}" --build-arg=NEXT_PUBLIC_API_KEY="$${NEXT_PUBLIC_API_KEY}" --build-arg=NEXT_PUBLIC_MESSAGING_SENDER_ID="$${NEXT_PUBLIC_MESSAGING_SENDER_ID}" --build-arg=NEXT_PUBLIC_APP_ID="$${NEXT_PUBLIC_APP_ID}" --build-arg=NEXT_PUBLIC_MEASUREMENT_ID="$${NEXT_PUBLIC_MEASUREMENT_ID}" .'
      ]
    secretEnv:
      [
        "ONECADEMYCRED_PROJECT_ID",
        "ONECADEMYCRED_CLIENT_EMAIL",
        "ONECADEMYCRED_CLIENT_ID",
        "ONECADEMYCRED_CLIENT_X509_CERT_URL",
        "ONECADEMYCRED_PRIVATE_KEY",
        "ONECADEMYCRED_PRIVATE_KEY_ID",
        "NEXT_PUBLIC_API_KEY",
        "NEXT_PUBLIC_MESSAGING_SENDER_ID",
        "NEXT_PUBLIC_APP_ID",
        "NEXT_PUBLIC_MEASUREMENT_ID"
      ]
  # Push the container image to Container Registry
  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["push", "gcr.io/visualexp-a7d2c/knowledge"]
  # Deploy container image to Cloud Run
  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   entrypoint: gcloud
  #   args:
  #     [
  #       "run",
  #       "deploy",
  #       "knowledge",
  #       "--image",
  #       "gcr.io/visualexp-a7d2c/knowledge",
  #       "--region",
  #       "us-central1",
  #     ]
images:
  - gcr.io/visualexp-a7d2c/knowledge
availableSecrets:
  secretManager:
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_PROJECT_ID/versions/1
      env: "ONECADEMYCRED_PROJECT_ID"
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_CLIENT_EMAIL/versions/1
      env: "ONECADEMYCRED_CLIENT_EMAIL"
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_CLIENT_ID/versions/1
      env: "ONECADEMYCRED_CLIENT_ID"
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_CLIENT_X509_CERT_URL/versions/1
      env: "ONECADEMYCRED_CLIENT_X509_CERT_URL"
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_PRIVATE_KEY/versions/1
      env: "ONECADEMYCRED_PRIVATE_KEY"
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_PRIVATE_KEY_ID/versions/1
      env: "ONECADEMYCRED_PRIVATE_KEY_ID"
    - versionName: projects/141114383555/secrets/NEXT_PUBLIC_API_KEY/versions/1
      env: "NEXT_PUBLIC_API_KEY"
    - versionName: projects/141114383555/secrets/NEXT_PUBLIC_MESSAGING_SENDER_ID/versions/1
      env: "NEXT_PUBLIC_MESSAGING_SENDER_ID"
    - versionName: projects/141114383555/secrets/NEXT_PUBLIC_APP_ID/versions/1
      env: "NEXT_PUBLIC_APP_ID"
    - versionName: projects/141114383555/secrets/NEXT_PUBLIC_MEASUREMENT_ID/versions/1
      env: "NEXT_PUBLIC_MEASUREMENT_ID"
