import React, { useEffect } from "react";
import { useParams } from "react-router-dom";

import axios from "axios";

import Paper from "@mui/material/Paper";

import Typography from "./modules/components/Typography";
import PagesNavbar from "./PagesNavbar";

const InviteStudents = props => {
  const { instructorId, collection } = useParams();

  useEffect(() => {
    const func = async () => {
      const invokeLink = document.getElementById("invoke-invite-email");
      if (invokeLink) invokeLink.click();
      await axios.post("/trackStudentInvite", {
        id: instructorId,
        collection
      });
      window.close();
    };
    func();
  }, []);
  const emailToStudentsText =
    "Dear research enthusiasts, \n" +
    "We are a research group at the University of Michigan, School of Information. " +
    "We would like to invite your students to join our online research communities and collaborate with us on research literature review on your desired topics. \n" +
    "We have developed an online platform for collaborative learning and research, called 1Cademy (more information at https://1cademy.us/home ). Since Fall 2020, out of more than 10,000 students who applied, 1,490 talented students from 144 schools have joined 1Cademy to collaboratively summarize, visualize, and present books and research papers on a weekly basis and get constructive feedback about their research. " +
    "You can check out our existing research communities https://1cademy.us/home#CommunitiesSection and search through the 1Cademy Knowledge Graph at https://node.1cademy.us to learn more about the content generated by students. " +
    "We also have community leadership opportunities for qualified students to lead our existing communities or establish new research communities. \n" +
    "You can learn more about our platfrom, research communities, and the application process at https://1cademy.us/home \n \n" +
    "Best regards, \n" +
    "1Cademy Research Communities \n" +
    "The University of Michigan, School of Information";
  return (
    <div>
      <a
        id="invoke-invite-email"
        href={`mailto:?subject=1Cademy Internship Research Opportunities at the Univerisity of Michigan School of Information&body=${emailToStudentsText}`}
        target="_blank"
      ></a>
    </div>
  );
};

export default InviteStudents;
