name: Knowledge Testing
on:
  pull_request:
    branches:
      - develop

env:
  CI_TEST: true

defaults:
  run:
    working-directory: .

jobs:
  tests:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install --legacy-peer-deps
          CI=false npm run build:prod
      - name: Unit tests
        run: |
          cd functions
          npm install --legacy-peer-deps
          npm i -g firebase-tools
          NODE_OPTIONS="--max_old_space_size=4096" firebase emulators:exec  --project test --only auth,firestore 'npx jest --ci --runInBand'
